# 项目名称, 会用来向Jumpserver注册, 识别而已, 不能重复
name: kubejump

# 启动时绑定的ip, 默认 0.0.0.0
bind_host: 0.0.0.0

# 监听的SSH端口号, 默认2222
sshd_port: 2222

# 监听的HTTP/WS端口号，默认5000
httpd_port: 8081

# 设置日志级别 [DEBUG, INFO, WARN, ERROR, FATAL, CRITICAL]
log_level: INFO

# SSH连接超时时间 (default 15 seconds)
ssh_timeout: 15

# 语言 [en,zh]
# LANGUAGE_CODE: zh

# SFTP是否显示隐藏文件
# SFTP_SHOW_HIDDEN_FILE: false

# 是否复用和用户后端资产已建立的连接(用户不会复用其他用户的连接)
# REUSE_CONNECTION: true

# 资产加载策略, 可根据资产规模自行调整. 默认异步加载资产, 异步搜索分页; 如果为all, 则资产全部加载, 本地搜索分页.
# ASSET_LOAD_POLICY:

# zip压缩的最大额度 (单位: M)
zip_max_size: 1024M

# zip压缩存放的临时目录 /tmp
zip_tmp_path: /tmp

# 向 SSH Client 连接发送心跳的时间间隔 (单位: 秒)，默认为30, 0则表示不发送
client_alive_interval: 30

# 向资产发送心跳包的重试次数，默认为3
retry_alive_count_max: 3

# 会话共享使用的类型 [local, redis], 默认local
share_room_type: local

# Redis配置
# REDIS_HOST: 127.0.0.1
# REDIS_PORT: 6379
# REDIS_PASSWORD:
# REDIS_CLUSTERS:
# REDIS_DB_ROOM:

# Mysql配置
database_name: "devops"
database_port: 3306
database_address: "192.168.1.105"
database_password: "root"
database_user: "root"

# 是否开启本地转发 (目前仅对 vscode remote ssh 有效果)
# ENABLE_LOCAL_PORT_FORWARD: false

# 是否开启 针对 vscode 的 remote-ssh 远程开发支持 (前置条件: 必须开启 ENABLE_LOCAL_PORT_FORWARD )
# ENABLE_VSCODE_SUPPORT: false